backend:
  name: github
  repo: lukegiuff/kinoora  # Your GitHub repository
  branch: main
  base_url: https://decap-proxy-kinoora.giuffa88.workers.dev  # Your deployed worker URL
  auth_endpoint: /auth

local_backend: false
site_url: "https://kinoora.com"  # UPDATE: Replace with your domain
display_url: "https://kinoora.com"  # UPDATE: Replace with your domain
media_folder: "public/assets/images"
public_folder: "/assets/images"

collections:
  - name: "config"
    label: "Site Configuration"
    files:
      - file: "content/config/site.json"
        label: "Site Settings"
        name: "site"
        fields:
          - {label: "Site Title", name: "title", widget: "string", default: "kinoora"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Site URL", name: "url", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image", required: false}
          - label: "Images"
            name: "images"
            widget: "object"
            fields:
              - {label: "Hero Background Image", name: "heroImage", widget: "image", default: "/assets/images/hero_image.png", hint: "Main hero section background image displayed on homepage"}
              - {label: "Founder Photo", name: "founderPhoto", widget: "image", default: "/assets/images/Daniel.jpg", hint: "Photo of the founder displayed on the About page"}
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - {label: "Footer Logo", name: "logo", widget: "image", default: "/assets/images/Kinoora_Logo_White.png", hint: "Logo displayed in footer (white version recommended)"}
              - {label: "Company Description", name: "description", widget: "text", default: "Redefining how independent films, series, and shorts are made, shared, and discovered."}
              - {label: "Launch Timeline", name: "launchTimeline", widget: "string", default: "Launching Q4 2025 in the EU and UK"}
              - {label: "Copyright Text", name: "copyright", widget: "string", default: "© 2025 kinoora. Empowering independent creators."}
              - label: "Section Headings"
                name: "sectionHeadings"
                widget: "object"
                fields:
                  - {label: "Creators Section Heading", name: "creators", widget: "string", default: "For Creators"}
                  - {label: "Viewers Section Heading", name: "viewers", widget: "string", default: "For Viewers"}
                  - {label: "Connected Section Heading", name: "connected", widget: "string", default: "Stay Connected"}
                  - {label: "Legal Section Heading", name: "legal", widget: "string", default: "Legal Notice"}
              - label: "Social Media"
                name: "socialMedia"
                widget: "object"
                fields:
                  - {label: "Twitter/X URL", name: "twitter", widget: "string", required: false, default: "#"}
                  - {label: "Instagram URL", name: "instagram", widget: "string", required: false, default: "#"}
                  - {label: "LinkedIn URL", name: "linkedin", widget: "string", required: false, default: "#"}
                  - {label: "YouTube URL", name: "youtube", widget: "string", required: false, default: "#"}
                  - {label: "Facebook URL", name: "facebook", widget: "string", required: false, default: "#"}
              - label: "Company Information"
                name: "companyInfo"
                widget: "object"
                fields:
                  - {label: "Company Name", name: "name", widget: "string", default: "kinoora GmbH"}
                  - {label: "Address", name: "address", widget: "string", default: "Orsoyer Str. 3, 40474 Düsseldorf"}
                  - {label: "Email", name: "email", widget: "string", default: "hello@kinoora.com"}
                  - {label: "Managing Director", name: "director", widget: "string", default: "Daniel Breuer"}
                  - {label: "Registration", name: "registration", widget: "string", default: "HRB 109481 Amtsgericht Düsseldorf"}
              - label: "Footer Navigation"
                name: "navigation"
                widget: "object"
                fields:
                  - label: "For Creators"
                    name: "creators"
                    widget: "list"
                    fields:
                      - {label: "Label", name: "label", widget: "string"}
                      - {label: "URL", name: "url", widget: "string"}
                    default: 
                      - {label: "Founding Filmmaker Program", url: "/filmmakers#founding-program"}
                      - {label: "Why Choose Kinoora", url: "/filmmakers#why-choose-kinoora"}
                  - label: "For Viewers"
                    name: "viewers"
                    widget: "list"
                    fields:
                      - {label: "Label", name: "label", widget: "string"}
                      - {label: "URL", name: "url", widget: "string"}
                    default:
                      - {label: "Join Waitlist", url: "/viewers#early-adopter"}
                      - {label: "Early Adopter Perks", url: "/viewers#early-adopter"}
                  - label: "Stay Connected"
                    name: "connected"
                    widget: "list"
                    fields:
                      - {label: "Label", name: "label", widget: "string"}
                      - {label: "URL", name: "url", widget: "string"}
                    default:
                      - {label: "Sign up for our Newsletter", url: "/#newsletter"}

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    identifier_field: "slug"
    summary: "{{slug | upper}} - {{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}



 